export const SET_THRESHOLD = 'SET_THRESHOLD';
export const RESET_THRESHOLD = 'RESET_THRESHOLD';

export const START_FETCHING_DATA = 'START_FETCHING_DATA';
export const ERROR_FETCHING_DATA = 'ERROR_FETCHING_DATA';
export const SUCCESS_NEW_POINT = 'SUCCESS_NEW_POINT';
